#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string


# updating before running the installtion commands.
sudo apt-get update
sudo apt-get install -y nginx

#creating an index html page with Hello World!
echo "Hello world!" | sudo tee /var/www/html/index.html

# performing a permaant redirection 301
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/SliEl permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
# creating a custom 404 doesn't exist page!
echo "This page doesn't exist!\n" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

# set a custom response http header

sudo sed -i "server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#testing nginx for syntax error
sudo nginx -t
# restart nginx after implementing the changes.
sudo service nginx restart